### ISSUE TITLE
Answering "no" when verifying tx leads to panic

### ISSUE THREAD

**Issue by mdyring** [e-money/em-ledger#1]
```
confirm transaction before signing and broadcasting [y/N]: 
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/cosmos/cosmos-sdk/client/input.GetConfirmation(0xf21211, 0x33, 0xc000a7ab90, 0xc000b4c000, 0x1000, 0x1000)
	/tmp/gopath/pkg/mod/github.com/cosmos/cosmos-sdk@v0.36.0-rc1/client/input/input.go:78 +0x1f7
github.com/cosmos/cosmos-sdk/x/auth/client/utils.CompleteAndBroadcastTxCLI(0xc00092b240, 0x11c3240, 0xc000461c60, 0x9, 0x0, 0x30d40, 0x3ff0000000000000, 0x0, 0x7ffd9198e8d1, 0xc, ...)
	/tmp/gopath/pkg/mod/github.com/cosmos/cosmos-sdk@v0.36.0-rc1/x/auth/client/utils/tx.go:89 +0x9f0
github.com/cosmos/cosmos-sdk/x/auth/client/utils.GenerateOrBroadcastMsgs(0xc000476930, 0x11c8220, 0xc0000e6c90, 0x0, 0x0, 0x11ad680, 0xc00000e018, 0xef0466, 0x4, 0x0, ...)
	/tmp/gopath/pkg/mod/github.com/cosmos/cosmos-sdk@v0.36.0-rc1/x/auth/client/utils/tx.go:40 +0x15f
github.com/cosmos/cosmos-sdk/x/staking/client/cli.GetCmdCreateValidator.func1(0xc000998500, 0xc000934500, 0x0, 0x14, 0x0, 0x0)
	/tmp/gopath/pkg/mod/github.com/cosmos/cosmos-sdk@v0.36.0-rc1/x/staking/client/cli/tx.go:60 +0x312
github.com/spf13/cobra.(*Command).execute(0xc000998500, 0xc0009343c0, 0x14, 0x14, 0xc000998500, 0xc0009343c0)
	/tmp/gopath/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:826 +0x473
github.com/spf13/cobra.(*Command).ExecuteC(0xc0000ec780, 0x24, 0xc000b91bb8, 0xf08e41)
	/tmp/gopath/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2f8
github.com/spf13/cobra.(*Command).Execute(0xc0000ec780, 0x1, 0xc00000ebc8)
	/tmp/gopath/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864 +0x2b
github.com/tendermint/tendermint/libs/cli.Executor.Execute(0xc0000ec780, 0x10deaf8, 0x2, 0xc000b91170)
	/tmp/gopath/pkg/mod/github.com/tendermint/tendermint@v0.32.1/libs/cli/setup.go:89 +0x4e
main.main()
	/tmp/em-ledger/cmd/cli/main.go:57 +0x357
```

**Comment by haasted** [comment]
Attempt to fix the issue upstream https://github.com/cosmos/cosmos-sdk/pull/4919

**Comment by haasted** [comment]
Fixed in SDK.
